# Generated by Django 5.0.1 on 2024-01-25 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='author/')),
                ('description', models.TextField()),
                ('content', models.TextField()),
                ('facebook_url', models.CharField(max_length=255)),
                ('twitter_url', models.CharField(max_length=255)),
                ('instagram_url', models.CharField(max_length=255)),
                ('pinterest_url', models.CharField(max_length=255)),
                ('is_top', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
